// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8PwZXN-dh_fL94THhj4X7_EHulvay6J8',
    appId: '1:717813736179:web:a7974d090bbaedfe664d86',
    messagingSenderId: '717813736179',
    projectId: 'ayrastore-d2128',
    authDomain: 'ayrastore-d2128.firebaseapp.com',
    storageBucket: 'ayrastore-d2128.appspot.com',
    measurementId: 'G-EYRCYWTVPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACIOqZFXKv_5M5HJkhM1t2IMj5LgmKoIM',
    appId: '1:717813736179:android:b52757c98b6fe5ae664d86',
    messagingSenderId: '717813736179',
    projectId: 'ayrastore-d2128',
    storageBucket: 'ayrastore-d2128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7dOPopzhQJUTCr548L2y0ZlmnPCnJIv8',
    appId: '1:717813736179:ios:10ab62f36e8d19c8664d86',
    messagingSenderId: '717813736179',
    projectId: 'ayrastore-d2128',
    storageBucket: 'ayrastore-d2128.appspot.com',
    iosBundleId: 'com.example.ayrastore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7dOPopzhQJUTCr548L2y0ZlmnPCnJIv8',
    appId: '1:717813736179:ios:5e5500346a104ef5664d86',
    messagingSenderId: '717813736179',
    projectId: 'ayrastore-d2128',
    storageBucket: 'ayrastore-d2128.appspot.com',
    iosBundleId: 'com.example.ayrastore.RunnerTests',
  );
}
